### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#108]
There's _a lot_ of new stuff which should be made into official release as soon as possible in order to keep the changelog in sane size.

A (hopefully not very growing) list of things to do:

General:
- [x] At least somewhat usable MSVC 2015 support (#96)
- [x] ~~Update~~ Get rid of `compatibility` branch
- [x] ~~Revive (P)NaCl support as GCC 4.4 support was dropped~~ later
- [x] Publicly available _and green_ CI for _all_ platforms (#99)
- [x] Code coverage on coveralls.io?
- ~~Put documentation on readthedocs.org~~ (fixed some other way, see #113)
- [x] Fix currently pending issues and TODOs
- [x] Stabilize new APIs
- [x] ~~Drop stuff that's long deprecated~~ after the release
- [x] Update copyright year to 2017
- [x] Make changelogs part of Doxygen docs

Corrade:
- [x] Add planned `--skip-tests`, `--skip-benchmarks` and `--no-xfail` options to TestSuite tester executables (mosra/corrade@c9208a8b13863f117b7f49576d2abbddd756f8e9, mosra/corrade@00249f263d18aa912e240e38a1cba8922ec37c60)
- [x] Something's wrong with recent Emscripten builds (Utility::Resource) (mosra/corrade@a330b4a78d697bb8a7deae89ba6f292a4433a282)
- [x] Update TestSuite documentation to mention colored output, instanced tests, repeating and benchmarks (mosra/corrade@f37f624e6207a2f91e33f819a9f755a26257c7c8)
- [x] ~~Plugin initialization/finalization is broken by design (e.g. unloading `HarfBuzzFont` finalizes `FreeType` library)~~ postponed

Core lib:
- [x] ~~Finish~~ Fix pixel storage support so it passes the tests at least on one platform (#104)
- [x] `magnum-imageconverter` utility
- [x] ~~"OpenGL 2015" and OpenGL ES 3.2 support (just a few new function aliases)~~ postponed, see #231 
- [x] Finish Windows Store/Phone support (a4d3beb0c3c718ce7cd38a537fc9be7d27235215)
- [x] ~~`WindowlessXEglApplication` to be able to run utilities on embedded Linux devices~~ we have `WindowlessEglApplication` and that should be enough I think
- [x] Compute shader tests fail on NV (ad962415a211307f1292f2f02f8739dfa4ae4370)
- [x] `Container::Array` instances returned from plugin crash on dangling deleter pointer after a plugin is unloaded (mosra/corrade@43397de88223c398b485a512d8c55c64c3b1b4ff)
- [x] ~~Finish unhandled cases in `DebugTools::textureImage()`~~ postponed
- [x] Implement compressed subimage queries to finally have complete textures (affected by a bug on NVidia) (645edecbcdc76902e80634bcc54782544512cf0a)
  - [x] which means adding a clean way for driver workarounds and ability to selectively disable them from command-line (356491e1dfb74df635fe607fc2f75a6989278e1c)
  - [x] and from environment to have all cases conveniently batch-testable (707d1d084d20c5c98814873e7b1dc24cc29623f9)

Plugins:
- [x] Merge DDS importer (mosra/magnum-plugins#7)
- [x] Add AnyImageConverter and AnyAudioImporter
- [x] Make StbImageConverter produce also other image formats (mosra/magnum-plugins@332ba6cec42f7590fcbf7d1ff94aedeac046c39d)
  - [x] Ability to get alias name from plugin manager (mosra/corrade@834ea41c1c2c1fe7d12b6bf62a7efd2ec08b9a1e)
- [x] ~~Implement StbDxtImageConverter using `stb_dxt` and (dynamically) use it in DdsImageConverter (should be easy as the other way around is already done)~~ postponed

Examples:
- [x] Port Audio example to Emscripten (should be fun)
- [x] Check what's new in WebGL 2 land (mosra/magnum-examples#12)
- [x] Picking example broken on Mesa (04983da23a503d68bddcc0ab416c81bf22a9f910 and mosra/magnum-examples@9f05e1c42ae5849f88e8e691ae1b8c86dbe1f933)

Integration:
- [x] Stabilize OvrIntegration API and ~~update to 0.7 (mosra/magnum-integration#7)~~ ~~0.8 (mosra/magnum-integration#10, mosra/magnum-examples#19)~~ 1.3 (mosra/magnum-integration#12, mosra/magnum-examples#22), hopefully they will finally stop completely breaking the API with each new release

**Comment by Squareys** [comment]
Integration (continued):
- [ ] Update OvrIntegration to 0.8

**Comment by mosra** [comment]
Windows Phone/Store support done in a4d3beb0c3c718ce7cd38a537fc9be7d27235215, another step closer to a release!

**Comment by mosra** [comment]
More transparent way to handle driver workarounds done in 356491e1dfb74df635fe607fc2f75a6989278e1c. Tiny but important feature.

**Comment by mosra** [comment]
Ability to disable extensions done in 9e4a86cc7c3b6d802a7e1ae8e6a2108b40d28448, a counterpart to transparent driver workarounds.

**Comment by mosra** [comment]
Compressed texture subimage queries done in 645edecbcdc76902e80634bcc54782544512cf0a, disabling extensions/workarounds from environment done in 707d1d084d20c5c98814873e7b1dc24cc29623f9.

**Comment by Squareys** [comment]
I would suggest to drop the following items from the list, since the last release has now almost been a year ago:

 - magnum-imageconverter utility
 - WindowlessXEglApplication to be able to run utilities on embedded Linux devices
 - "OpenGL 2015" and OpenGL ES 3.2 support (just a few new function aliases)
 - Make StbImageConverter produce also other image formats
 - Implement StbDxtImageConverter using stb_dxt and (dynamically) use it in DdsImageConverter
 - Port Audio example to Emscripten (should be fun)
 - Check what's new in WebGL 2 land (mosra/magnum-examples#12)

Or in general, I feel our strategy should be: Don't add new stuff for this release, but fix existing and remove old stuff :)

I know that list is pretty radical, but many simple todos still add up. Also, it's just a suggestion, of course.

Also "Update copyright year" has been done, right?

**Comment by mosra** [comment]
Agreed.

Currently it's more like "I need this feature right now so I'll implement it" and not much time left for fixing lower priority issues and writing changelogs. The single most important TODO for the snapshot now is just this:

* Making everything working on Windows with MSVC >=2013, Linux with GCC >= 4.7, OSX, iOS, Android, Emscripten and NaCl

If that's achieved, I'll make a snapshot.

Dropping GCC <=4.6 support is I guess sane thing to do, but I need to keep the workarounds that were needed for MSVC 2013. Then, because NaCl had GCC 4.4, I need to switch to PNaCl that has newer compiler, which means more testing and CMake wrangling to make the toolchain working. I didn't test on Android for a while and Emscripten compiler seemed to have issues with `Utility::Resource` lately, maybe that's fixed now.

**Comment by mosra** [comment]
"Failing" compute shader tests fixed in ad962415a211307f1292f2f02f8739dfa4ae4370. Of course it was my fault the whole time. 258ab1a92cd41bac8052f3207fd50b0efb724efe added countermeasures to avoid accessing data of rvalue `Image*` instances so this doesn't happen *ever* again.

**Comment by mosra** [comment]
`--skip-tests`, `--skip-benchmarks` and `--no-xfail` options for TestSuite tester executables added in mosra/corrade@c9208a8b13863f117b7f49576d2abbddd756f8e9 and mosra/corrade@00249f263d18aa912e240e38a1cba8922ec37c60. So little yet so powerful.

**Comment by mosra** [comment]
`Utility::Resource` is finally fixed on Emscripten in mosra/corrade@a330b4a78d697bb8a7deae89ba6f292a4433a282. It was (of course) alignment problem. The Emscripten builds are also now being added on AppVeyor CI, so it should result in more stable experience in the future.

cc: @smspillaz

**Comment by smspillaz** [comment]
Thanks!

-- 
Sam Spilsbury

**Comment by mosra** [comment]
Object Picking Example fixed in 04983da23a503d68bddcc0ab416c81bf22a9f910 and mosra/magnum-examples@9f05e1c42ae5849f88e8e691ae1b8c86dbe1f933.

**Comment by mosra** [comment]
Crash in Array destructor with dangling deleter pointer on plugin unload fixed in mosra/corrade@43397de88223c398b485a512d8c55c64c3b1b4ff.

**Comment by mosra** [comment]
Code coverage for all repos done now (except examples, where it does not make much sense).

**Comment by mosra** [comment]
Image converter utility added in 0e2d28130c60fbc999e98879ffc51ced34c64207.

**Comment by mosra** [comment]
As of now, all `compatibility` branches are dropped and all references to them were removed from the documentation.

**Comment by mosra** [comment]
Last known bugs with pixel storage were fixed in 1cfd2dc7b5c361e10d36c4a5f6569646fc0e00b2 and d998cb0f769854973412032ae673eaadfb5b3a84.

**Comment by mosra** [comment]
Corrade::TestSuite documentation improvements done in mosra/corrade@f37f624e6207a2f91e33f819a9f755a26257c7c8.

**Comment by mosra** [comment]
Ability to get alias name from plugin manager done in mosra/corrade@834ea41c1c2c1fe7d12b6bf62a7efd2ec08b9a1e and the StbImageImporter plugin was reworked to handle also other formats in mosra/magnum-plugins@332ba6cec42f7590fcbf7d1ff94aedeac046c39d.

**Comment by mosra** [comment]
CIs are done, Audio and other WebGL 2 stuff is on Emscripten now, changelogs were moved to Doxygen. The only remaining thing is some initial support for ES3.2/GL4.6 (so it doesn't advertise stuff that's >3 years old), the rest can be done later.

**Comment by mosra** [comment]
2018.02 is out, release announcement is at http://blog.magnum.graphics/announcements/2018.02/ .

Don't tell anybody it took me three years :see_no_evil: :D
