### ISSUE TITLE
Using Sphinx/Breathe/ReadTheDocs for documentation

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#113]
Doxygen is great tool for making documentation of C/C++ projects. The parsing and formatting capabilities are unmatched by anything else. However, some people say that the Doxygen HTML output is far from perfect, hard to navigate etc. The most recommended alternative "frontend" is [Sphinx + Breathe](http://breathe.readthedocs.org/en/latest/), possibly being hosted (and automatically updated) on http://readthedocs.org.

I briefly tried to render [Corrade](https://github.com/mosra/corrade) documentation ([live version](http://corrade.readthedocs.org)) with it and found a few major issues that currently prevent me from using it for production purposes:
- [ ] Everything is either shoveled onto single page (which is unberable even with small_-ish_ project like Corrade) or I have to manually create an `.rst` file listing namespaces/types/function/etc. to achieve some subpaging. The projects have hundreds of types, making such option _very_ hard to maintain. Alternative might be to use Doxygen grouping or some hand-written Python script that parses the XML and creates files (ugh). Possibly related issues: https://github.com/michaeljones/breathe/issues/18, https://github.com/michaeljones/breathe/issues/38
- [ ] No `doxygenpage`-like Sphinx command to reference Doxygen pages. I might be able to work around this using `doxygenfile`, but that might not cover all use cases
- [ ] The documentation combines two kinds of anchors, one Doxygen-style (`#CorradeclassCorrade_1_1Containers_1_1Array_1a4fcbcb24d5a462f13e7dc8e138664e31`) for links from Doxygen documentation blocks and the other Sphinx-style (`#_CPPv2N7Corrade10Containers5Array5ArrayE12DefaultInitTNSt6size_tE`) for links from Sphinx headers. Weird and potential source of confusion/problems.
- [ ] Undocumented (unimplemented?) handling of tag files -- I want to have Corrade documentation separated from Magnum documentation, but be able to link from one to another. Possible with stock Doxygen, not sure here, need to test.
- [ ] Everything from a page after first heading is lost (for example, the main page has only two lines and the "Supported platforms" heading is nowhere to be found). Might be related: https://github.com/michaeljones/breathe/issues/116 (otherwise I should report it)
- [ ] Nonexistent C++ syntax highlighting: https://github.com/michaeljones/breathe/issues/123
- [ ] Broken math formula rendering (example: http://breathe.readthedocs.org/en/latest/latexmath.html)
- [ ] C++11 using directives are not rendered correctly: https://github.com/michaeljones/breathe/issues/213
- [ ] Maybe just a matter of styling/template, but, in comparison to default Doxygen output, the documentation wastes vertical space a lot (e.g. http://breathe.readthedocs.org/en/latest/inline.html), also weird styling inconsistencies between inline code blocks (red??), Doxygen code blocks (large??) and Markdown code blocks. Other than that it surely looks nicer than stock Doxygen.
- [ ] Private/undocumented members shown _by default_ (or at least when everything is in one page using `doxygenindex`). Related: https://github.com/michaeljones/breathe/issues/183
- [ ] Not sure about the Doxygen version that's used on readthedocs, but it prints _a lot_ of parser errors: https://readthedocs.org/projects/corrade/builds/3360973/

Maybe also worth reading: http://stackoverflow.com/a/5005195

As it currently stands, Sphinx/Breathe isn't ready to replace the default Doxygen HTML output. I might try to push it further later, but now there are other things that are in my opinion more important.

**Comment by LB--** [comment]
> some people say that the Doxygen HTML output is far from perfect, hard to navigate etc.

If the issue with doxygen output is just viewer navigation, couldn't that be fixed with some CSS styling? Or maybe I don't understand what the issue is?

**Comment by mosra** [comment]
If you compare for example http://mosra.cz/blog/corrade-doc/classCorrade_1_1Containers_1_1Array.html and http://corrade.readthedocs.org/en/latest/containers-array.html, the output on ReadTheDocs feels much lighter/less crowded while conveying the same information. 

Or maybe not. Depends on personal preference and what's one used to :)

**Comment by LB--** [comment]
Yeah, my point is why not fix the doxygen output with a custom stylesheet? From googling around it looks like lots of people have already written some, it could be as simple as copying an existing one with a permissive license.

**Comment by mosra** [comment]
Yup, something could be fixed with custom CSS stylesheet, but some hardcoded stuff will probably remain as is (border around each detailed function description, the overall layout etc). The question is now how much of the layout should be changed and what to leave as good enough.

Googled a few really good ones (e.g. https://biogearsengine.com/documentation/index.html), wow! I planned to create some "corporate identity" for the project, so the restyling might be done as a part of it.

**Comment by LB--** [comment]
I happened to come across [GitBook](https://www.gitbook.com/) which might be nice for high-level documentation, but I'm not sure it's a good replacement for doxygen.

**Comment by LB--** [comment]
I posted [this](https://www.reddit.com/r/cpp/comments/49nzf6/i_created_a_github_integration_for_doxygen_try_it/) in gitter but forgot to leave a comment here for historical reasons:
https://codedocs.xyz/ is designed for GitHub + Doxygen workflow and hosts documentation for you, updating after each push

**Comment by mosra** [comment]
From a brief look at codedocs it doesn't seem to support all features I need, among them:

- tag files to crosslink Corrade and Magnum documentation (crucial, I think)
- custom layout files to work around some rough edges

**Comment by mosra** [comment]
Ahhh, I wanted to close this issue for **so damn long**. Now is the time, finally.

To recap: Magnum docs at http://doc.magnum.graphics/ are now using a custom Doxygen theme that's developed as a part of the [m.css](http://mcss.mosra.cz) project. Submit further issues related to the theme to https://github.com/mosra/m.css or to https://github.com/mosra/magnum-website.

:champagne: :beers: :tumbler_glass:
