### ISSUE TITLE
2018.08 release

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#265]
After releasing 2018.04 I decided to have a bit more time to pull bigger features in and so 2018.06 was skipped. I don't want to take the release too long, so I'd like to have 2018.08 as the next release -- i.e., before the end of August.

What *needs* to be done:

- [ ] File callbacks for `Trade::AbstractImporter`
- [ ] Finish initial animation support and merge it to master (#191)
- [ ] glTF animation import (mosra/magnum-plugins#46)
- [ ] Create some advanced viewer/player app in the extras repository that's able to load models and play back their animations -- *very* important to actually verify both the usability of the API and correctness of its behavior
- [ ] *Visibly* deprecate old unmaintained functionality, remove it from packages and schedule it for complete removal in ~6 months (#148)
    - the `Shapes` library
    - the `ColladaImporter` plugin
    - the `Platform::GlutApplication` lib

What *should* be done (very good for marketing, but it's not extremely critical if this misses the milestone):

- [ ] Integrating the mouse controls example (mosra/magnum-examples#46)
- [ ] Integrating the Box2D example that I have in my e-mail inbox since March and didn't get to it yet (sorry)
- [ ] Integrate [minimp3](https://github.com/lieff/minimp3) for MP3 audio import
- [ ] Merge JpegImageConverter to support more screenshot options (mosra/magnum-plugins#26)

These lists might grow later. 

Apart from that there's a lot of other not-as-important things to add, but since I won't have time to anything extra, I won't list them here. As always, help is greatly appreciated -- and if anybody is willing to contribute, their name will be prominently mentioned in the release notes :)

**Comment by mosra** [comment]
Basic animation support (#191 and mosra/magnum-plugins#46) has been merged to master.

**Comment by mosra** [comment]
Majority of the JPEG export code from mosra/magnum-plugins#26 has been merged to master.

**Comment by mosra** [comment]
- Emscripten visuals were updated in b2cb689cdc2156608bfeda06e6bfc76e89a19eac
- Some HiDPI work done, see #243 for details -- still want to do also Windows support and GLFW implementation
- Phong alpha masking fixed in a1ef8550d36ba46be929e0078557b01c300e78f6
- GlutApplication deprecated in d70f75a179f05920da5dcf09c61dd268476328bf
- Assimp hidden root node workarounds to make DART integration working again are in mosra/magnum-plugins@93ac419df2072d1bd895682182fa86361e3573e2

**Comment by mosra** [comment]
Ui is DPI-aware since mosra/magnum-extras@87beabb3f8c885ef04165893a810fae98500ac92.

**Comment by mosra** [comment]
OVR integration update from mosra/magnum-integration#26 was merged and similar changes done in the examples repo in mosra/magnum-examples@1ea3c0e17c6b7f2d5d381c2283cdd86a15277e19 and mosra/magnum-examples@7bf00e0b0d7c121f27cd3417a5abe2181b54505a.

**Comment by mosra** [comment]
The `corrade-rc` utility is standalone since mosra/corrade@fb56f72eb24fa846313f662a37558cbbaf5c4221 and it's now also possible to compile only it, without any other libraries -- useful for crosscompiling.

**Comment by mosra** [comment]
`Magnum::Vk` library is now successfully compiling on Windows (and on AppVeyor) since d578d4d89e5f5b9ab0c73d1567bfafa19f530093 and 6f2b11595393542957ddb20ff3606a13fb9c0266. Thanks goes to @LB-- for figuring out the compiler command line.

**Comment by mosra** [comment]
@Squareys could you please test CMake 3.12 in combination with Emscripten on Windows? I remember there being issues with platform file ignored and thus no `*.bc` or `*.js` files generated. Can't reproduce this on Linux. 

Thanks a lot :+1:

**Comment by mosra** [comment]
`Magnum::Ui` now works again on 32bit Windows since mosra/corrade@b83c116754c92bcf57ccedf113657a75fc11e6f5. (Well, there's still that ugly workaround, but it'll be fixed soon after the release is out. Too fragile to break it again for the release.)

**Comment by mosra** [comment]
- PVS-Studio reports were accounted for in e7954783530a0fac7f24f81241a3d0e609468638, 471a6d0c28bccaa327d75d30b789f26df62ebdec, c0affdae3ba3c13535617e182fe7074b8f3b3d0f, 7356a1b788579ee4495f0d97da42557cb5478e90, 87a951fc5d3bd5e0672c31a02102bf0b45d08faf and mosra/corrade@623e5c2afa146dc53927897a9d7ce28cc78eeff9
- the `Shapes` library and `DebugTools::ShapeRenderer` is deprecated in 8efc6b39e902d01dfac904163ad90385d3007013
- Better `DebugTools` dependencies handling in `FindMagnum.cmake` is done in 2c56d1600a1fceea9eb8d4518d4b6b3f20769835
- Initial HiDPI support (Linux, macOS) in GlfwApplication is in dba35bac7a9c170931c476719e4781e501c92a65

**Comment by mosra** [comment]
- `ColladaImporter` is deprecated in mosra/magnum-plugins@35ee1a2665917c0246b02b108086a7ade88d1f0f
- `BulletIntegration::convertShape()` is deprecated in mosra/magnum-integration@968fa40c7fe58ae9efced185f91e47d0992589d9

**Comment by mosra** [comment]
Fuzzy tests for JPEG conversion from mosra/magnum-plugins#26 merged in mosra/magnum-plugins@228e2d43dd5ac2358c4089fb3024ff2e3a420f3b.

**Comment by mosra** [comment]
Okay, I'll stop pretending I can make the release in August.

Spline interpolation from #267 is integrated now; docs are updated with [all the fresh new stuff](http://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1CubicHermite.html). And also with all the new deprecation warnings.

**Comment by mosra** [comment]
- MSVC compiler crash is fixed in b44166b23818bba62e6a0e4e7bcc4e6cd95c81ca
- glTF spline animation import is in mosra/magnum-plugins@0c55e3150213a19b5409c18e02c88f77a83cc06e
- glTF multi-primitive mesh loading is in mosra/magnum-plugins@da587349599f976894f5b96b10dc44bab0921d82
- glTF rotation track renormalization done in mosra/magnum-plugins@0ce845678c735845b71cf8b0e8c170491392eda0 (this finally makes it possible to play back the animated triangle sample, ugh)

Audio support on Android and the rest of animation stuff from #101 is scheduled for later, there's enough for this release already.

**Comment by mosra** [comment]
- [Vulkan Triangle](http://doc.magnum.graphics/magnum/examples-triangle-vulkan.html) example is integrated in mosra/magnum-examples@41c78efc69b2e8d2d0a85f0a45ceed2dc40b816d
- The [Example Index](http://doc.magnum.graphics/magnum/example-index.html) is now a gallery with pretty images
- glTF animation clip merging on import is one in mosra/magnum-plugins@2ee3000994ba9bf1cd2e3b3c961490bc1cb6f234
- visuals of Emscripten TestSuite browser executables were updated in mosra/corrade@8769546495b70d4ddef343291a7e9e02abc76a71
- Animation API unification done in e43d5790f606c8b13f29fde4a53a6a48361dd937

**Comment by Squareys** [comment]
> @Squareys could you please test CMake 3.12 in combination with Emscripten on Windows?

CMake 3.12.3 + Emscripten 1.38.6 worked great for compiling a project that uses Magnum. Or is this about compiling magnum itself?

**Comment by Squareys** [comment]
Compiling Corrade, Magnum, Magnum Plugins and Magnum Integration also worked fine and created .bc files.
