### ISSUE TITLE
2019.10 release

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#340]
It's becoming very unlikely that I'll be able to release 2019.0b until the end of May, which means no 2019.05. Because my OCD forces me to release on even-numbered months :laughing:, the next release will be ~~2019.07, optimistically at the beginning of July~~ ~~well... 2019.09.~~ Actually, what's wrong with 2019.10?

Things to do (list expected to grow *slightly*):

- [x] Finalize initial Python bindings and put them into master (mosra/magnum-bindings#1)
  - [x] Bind shader APIs
  - [x] Bind also textures and images, importers
  - [x] Look into faster buffer protocol
  - [x] Finish search and symbol crosslinking for Python docs
  - [x] Windows support (mosra/magnum-bindings#2)
  - [x] Port the textured triangle and viewer examples
  - [x] And publish a blog post
  - [x] Expose remaining primitives -- mosra/magnum-bindings@e334cc17b247697ec6f0d5294f96952451b4d689
  - [x] The Windows static build on CI gets stuck when running Magnum tests -- mosra/corrade@01d8cdd30cf9c51e3abc9280f7a6da6ad8c926b4, 909887ad7c05c92ba7904b5d443d9716ce8ddf06
- [x] Fix issues with multiple Context instances when having multiple `*.so`s with static Magnum (weak symbols, hopefully?) -- mosra/corrade@1bef56947f30fba91e448fe6e5561341a83c18d2, e52c9e8d9ee21a81f02cfabe631323d89dcfef7a
  - [x] Explicit static build testing for this in Corrade (plugin managers, Debug) and Magnum (GL/Audio Context) -- mosra/corrade@21ec22720f66bfe41d46a87b40ee3e0efc35c571, 59aade762a2996d336da522a9243697b1f87571c
  - [x] Make this work on Windows as well (`thread_local`s can't be dllexported and this damn platform doesn't have weak symbols, so this needs to be a crazy mess of DllMain and calling GetProcAddress on itself) -- mosra/corrade@7b98f1983cb1778a9cbb38184c42705320e0a266, 24f7d45364510a4521a2cb70ed5600a7a83bb142
- [x] Update for MSVC 2019 support (#343)
  - [x] Test on the CIs
  - [x] Adapt bootstrap projects (and add MSVC2019 CI for them) #354
- [x] Integrate the DART example (mosra/magnum-examples#63)
  - [x] And the blog post :)
- [x] Mention MeshTools::compile() in the Primitives example -- mosra/magnum-examples@92fd404e988f767900b9262e46f2c07fb181ebab
- [x] Mention that one can use Shaders::Flat for the textured triangle example as well
- [x] ~~A simple framebuffer example (the motionblur one is *not* simple),~~ simpler docs for the GL::Framebuffer class -- dbb4cb39a13e77f328ad4c33f0ae15b4aed255ba
- [x] Update ImGui to latest version, link proper frameworks on macOS (mosra/magnum-integration#48)
- [x] Merge Emscripten application (#300 and related PRs in other repos)
  - [x] And publish a blog post, ideally -- https://blog.magnum.graphics/announcements/new-emscripten-application-implementation/
- [x] Everything else in the 2019.0b milestone
  - [x] ~~vcpkg doc improvements https://github.com/mosra/magnum/pull/368~~ postponed
  - [x] ~~look into emscripten issues https://github.com/mosra/magnum/issues/376~~ postponed
  - [x] ~~finish the resourcemanager iteration https://github.com/mosra/magnum/pull/364, https://github.com/mosra/magnum/issues/363 (I should have a branch with it)~~ postponed, not time-critical
  - [x] ~~https://github.com/mosra/magnum-integration/issues/55~~ postponed
  - [x] https://github.com/mosra/magnum-bindings/issues/6
- [x] ~~Finish MeshData rework to support memory-mapped data and not require STL containers~~ postponed: #371 
  - [x] ~~Rework MeshTools to not require STL containers~~
  - [x] ~~Introduce a MeshConverter plugin interface (and integrate zeux's meshoptimizer through that)~~
  - [x] ~~And publish a blog post :sweat_smile:~~
- [x] Enable GlfwApplication in all packages, because people like to use it -- 8110de3838fef5a4ae440a64e7e4ee313abb058c
- [x] ~~Conan package? #304~~ postponed
- [x] Make it possible to disable all `install()` commands for cmake subproject users (or does `EXCLUDE_FROM_ALL` handle that? -- yes it does!)
- [x] Workaround Windows AMD issue with CubeMapTexture and setStorage() (reuse some Intel workarounds?) -- ca326fdb1869260754ec7156058c0c676d1fc5a1
- [x] Try to reproduce and workaround Intel issue with Text example not rendering anything with DSA (on version 26, v23 works) -- can't reproduce on v26 (maybe the recent various shader fixes did the trick?)
- [x] ~~Look into BufferTexture crashes on macOS (someone / some company needs to buy me a Mac)~~ nobody bought me a mac :cry: 
- [x] Make usage with CMake subprojects less shitty (#357, mosra/magnum-plugins#63, ...)
  - [x] if a subproject setup is detected, put all binaries into `${CMAKE_BINARY_DIR}/bin`, for example, and plugins into a corresponding subdirectories -- mosra/corrade@73d3f31d3ef949e2ba0da1ac46967175bfb4a377 and similar in other repos
  - [x] ~~Bundle the metadata into the binary so it doesn't have to be dragged around (reuse `corrade-rc`, add `--tool [compile|embed|extract]` to it, for example, append with some magic around (`0x1c0ffee1<file-offset>1c0ffee1` on both sides, e.g.), but still make it possible to have that file externally for manual updates~~ postponed, with the change done in mosra/corrade@73d3f31d3ef949e2ba0da1ac46967175bfb4a377, it's a much smaller pain point than before and not sure if the benefit is worth the added complexity
- [x] Resolve issues with multiple PluginManager instances, make it reasonably thread-safe (mosra/corrade#65)
- [x] Complete shader tests for all other shaders
  - [x] ~~add benchmarks~~ postponed, too much work RN
- [x] ~~Look into Blinn-Phong, verify it's indeed faster (https://github.com/facebookresearch/habitat-sim/pull/152#issuecomment-522148874)~~ postponed, needs the benchmarks
- [x] ~~Version headers for all repos~~ postponed, not having a clear idea on how to do this w/o Git available (e.g. a ZIP source download)
- [x] fix too fast mouse clicks under ImGui (mouse press & release *can't* happen in the same frame) -- https://github.com/mosra/magnum-integration/commit/84fa6d84f5ac5bdbbcfd829e738e7fa6859d1b36
- [x] relative mouse movement in AndroidApplication (the primitives example `ports` branch doesn't build) -- 9fad16182ea36e80d2e76175ea43cd6b404d1445
- [x] implement https://github.com/graphitemaster/normals_revisited -- 515637c76aa8d72e525a86d4a09e6c350ef03b01
  - [x] use it instead of `rotationScaling()` for `setNormalMatrix()`
- [x] clarify SceneGraph `initialTransformationMatrix` -- it's not initial and it's not pre-transformed either -- 8c7c2c57451c35b911dc056474871d80c00c831e
- [x] reference Optional as a safer alternative (but with overhead) from all NoCreate constructors -- d06914a1bd2e4523e1a3ce21d163b57f46d0c7fb
- [x] Deprecate DebugTools resource manager singleton -- 607b3a15fa01b7856a26879fff0d09b57c0e8568
- [x] Gradle-less Android build for examples because I have no patience for that crap anymore -- mosra/magnum-examples@d64c155446c6c52215c955678dd483606364ac34
  - [x] And bootstrap project -- mosra/magnum-bootstrap@aba2e7bf3e35d7fdb00d627ba251b3290a7482cc
- [x] Copy Emscripten extra stuff into the build dir for all examples so it can be run from a build dir -- mosra/magnum-examples@09d5e01831b3f71272382bc121bfd78103972e51
  - [x] And for the bootstrap project -- mosra/magnum-bootstrap@9f44099f88c41147d91b4bb82c80e3c271830897, mosra/magnum-bootstrap@08a2558b40c7f3321d060199d57a2c974fd5978c
- [x] Remove now-unneeded NVidia EGL workaround (it was my bug, not NVidia's) -- 507c5bf7399a267ce549c753cf5e3376e51e6041

**Comment by mosra** [comment]
YAY, six stressful months of release preparation finally over. Tagged as `v2019.10` in all the repos. Package updates will follow, release announcement coming on Monday.
