### ISSUE TITLE
UTF-8 everywhere (or, more precisely, also on Windows)

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#98]
Along with other recent attempts to make these libraries actually usable on Windows (MSVC-related fixes, workarounds etc.), I'd like to have first-class UTF-8 support also on this platform (because it basically "just works" _everywhere else_). As you may already know, there is no such thing as using UTF-8 in WINAPI directly, you either use ANSI or UTF-16. Both are ugly and nasty, but UTF-16 is clearly the way to go (although there is _very_ little support for it in standard C++).

Recommended reading (the rest of the issue relies on decisions from this _manifesto_): http://utf8everywhere.org/

So, the goal is to have all text in `const char`/`std::string` _and_ in UTF-8, not to force UTF-16 onto the users like in Qt, Java and elsewhere. The actual problems:
- [x] File/directory operations (`Corrade::Utility::Directory`) -- accepting UTF-8 filenames, converting them to UTF-16 internally and explicitly using `*W` Windows APIs (instead of [these goddamn macros](https://twitter.com/FlohOfWoe/status/602113404267077632)), for directory listing converting the returned UTF-16 strings back to UTF-8. mosra/corrade@a1061d03a33c2ca4134e4b5bed627b083602bfeb
- [x] Loading of plugins from UTF-8 directories (`Corrade::PluginManager`) mosra/corrade@2328ba32ec4b81ebc6e5e14edddbee8e530e225e
- [x] UTF-8 environment variables in `Corrade::Utility::Arguments` mosra/corrade@49be6d0324505a489e3482284332583bc7a67774
- [x] UTF-8 filenames in `Corrade::Utility::Configuration` mosra/corrade@f2a9f1c6ca7309d66b7f291d3aa2c26e13f0aa2f
- [x] UTF-8 filenames passable to `corrade_add_resource()` mosra/corrade@b90f5b46ff8817776fcc117ab29aebdf3d7f9b7d
    - [ ] Test for that (mosra/corrade#49, currently causing infinite recursion w/ Ninja 😢)
- [x] ~~`std::[io]fstream` -- MSVC has non-standard constructor and `open()` that takes UTF-16 filename as a parameter, sadly nothing like that on MinGW (but there are [some](http://stackoverflow.com/questions/3471229/win32-c-fstream-wide-argument) [solutions](https://github.com/FFMS/ffms2/commit/d96070ddb08e82febc85df40e1ccebe9f60426b6)). This is  nothing clean, so the final solution is probably to move away from STL streams in importers etc. altogether and handle that some other way instead (which would be also far more portable to platforms w/o filesystem access). Done for Corrade in mosra/corrade@a1061d03a33c2ca4134e4b5bed627b083602bfeb (ensuring nobody else uses `fstream` directly).~~ obsoleted by #293, we moved to C I/O in https://github.com/mosra/corrade/commit/c1a5eedc039a2d7479a8a947ecd2d6985524cb55 (and it's UTF-8 aware as well)
  - [ ] Ensure no other library uses `fstream` or C I/O directly (plugins and 3rd party libs, especially)
- [x] UTF-8 `argc` and `argv` parameters. As with everything else, these "just work" everywhere except on Windows. I could probably do something similar to `SDLmain`, `QtMain` that would have `int wmain()` internally, converts the UTF-16 arguments to UTF-8 and calls the user-provided `main()` afterwards. I need to look into that more closely, because standard C++ allows some variations on `main()` such as implicit return statement and omitting `argc`/`argv`. Any tips on this would be greatly appreciated. MinGW doesn't support `wmain()`, but there is [a workaround](https://github.com/FFMS/ffms2/commit/d96070ddb08e82febc85df40e1ccebe9f60426b6). -- mosra/corrade#37
- [x] Proper `WinMain()`/`main()` wrapper on Windows. Currently it's only possible to create console applications using the `MAGNUM_APPLICATION_MAIN()` macro, because it uses `main()`. Calling `add_executable(something WIN32 ...)` then makes the MSVC linker complain about missing `WinMain()`. -- mosra/corrade#37
- [x] ~~Unicode standard output (`std::wcout`/`std::wprintf` etc.) that does _not_ depend on some random codepage setting in the terminal (whose "clever" idea was that, anyway). Most of (all?) the output is currently handled with `Corrade::Utility::Debug`, so that means just reworking the internals to produce UTF-16 on Windows. Standard input is probably not an issue here (these libraries have different scope).~~ AFAIK, this would mean redirecting to a file would make it UTF-16 encoded, which is *definitely not* wanted. Instead, set the output encoding to UTF-8 like in https://github.com/dart-lang/sdk/commit/92b746cd439d94a0ffea7f8bf45669c407acdc96#diff-5c4ad2f03f9aac0f124bf4e6dba66156. Tools like CTest already enable that on their own.

As UTF-8/UTF-16 conversion would be needed only on Windows, I'll use WINAPI functions to do the conversion and won't make any public API for this, because it _really_ shouldn't be needed anywhere else. I can't employ the (horrifically convoluted) `std::codecvt` etc., because (if I'm not mistaken) it is not supported in GCC < 4.9 (and probably also elsewhere), making it currently useless. (It's also awfully slow and the headers are bloated.)

Looking at the bigger picture, because it's apparently impossible to portably use `std::fstream`, `std::cout` etc. with proper UTF-8 filename/output on all platforms, I might as well get rid of the stream library altogether and have far lighter executables as a result.

**Comment by mosra** [comment]
Just found out about the need for proper `WinMain()` entry point on MSVC when building non-console apps, updated the issue above. 

Current workaround is to build applications with the ugly console window popping up in the background (i.e. without `WIN32` in CMake's `add_executable()` call), but that's not something I would want in the long run, so this issue is now rather high priority.

**Comment by mosra** [comment]
This was more painful than I thought (*especially* MinGW).

- Full UTF-8 support in `Utility::Directory` on Windows is done in mosra/corrade@a1061d03a33c2ca4134e4b5bed627b083602bfeb
- Opening UTF-8 filenames in `Utility::Configuration` on Windows is done in mosra/corrade@f2a9f1c6ca7309d66b7f291d3aa2c26e13f0aa2f
- Handling of UTF-8 environment variables in `Utility::Arguments` on Windows is done in mosra/corrade@49be6d0324505a489e3482284332583bc7a67774
- Ability to use `PluginManager` with UTF-8 paths on Windows is done in mosra/corrade@2328ba32ec4b81ebc6e5e14edddbee8e530e225e

**Comment by mosra** [comment]
*Finally* closing as resolved, the remaining things are done in mosra/corrade#37 (soon to be merged) and mosra/corrade#49 (will get merged in ~2100, probably, if not later).
