### ISSUE TITLE
Publicly available CI

### ISSUE THREAD

**Issue by mosra** [mosra/magnum#99]
Quite a long-running issue and things changed quite a lot since 2015, so I removed all the outdated info now. Things to do:

- [x] Linux build -- [Travis CI](http://travis-ci.com)
  - [x] Linux desktop GLES2 build
  - [x] Linux desktop GLES3 build ~~once I find more recent GL library~~ solved by switching to 14.04
  - [x] ~~Investigate GL testing ( https://docs.travis-ci.com/user/gui-and-headless-browsers/, https://github.com/travis-ci/travis-ci/issues/5645, https://github.com/travis-ci/travis-ci/issues/3524, swiftshader? )~~ postponed to #207
- [x] Mac OS X build -- also Travis CI ([system info](http://docs.travis-ci.com/user/osx-ci-environment/))
- [x] Android build -- [Travis CI](http://docs.travis-ci.com/user/languages/android/), in progress
  - [x] Build selected examples from the `ports` branch
- [x] iOS build -- Travis CI
  - [x] Build selected examples from the `ports` branch
- [x] Emscripten build -- Travis CI
  - [x] Build selected examples from the `ports` branch
- [x] ~~NaCl build -- ?? (probably Travis CI)~~ postponed, see #198
- [x] Windows build -- [AppVeyor](http://www.appveyor.com/), it has both MSVC and MinGW ([system info](http://www.appveyor.com/docs/installed-software))
  - [x] Switch to 64-bit MSVC
  - [x] Windows desktop GLES build
  - [x] ~~Windows ANGLE build~~ postponed, see #206
  - [x] ~~Investigate headless GL testing (http://help.appveyor.com/discussions/questions/2522-running-unit-tests-opengl, swiftshader?)~~ postponed to #207
- [x] Windows Phone/Store build -- AppVeyor
  - [x] ~~Build selected examples from the `ports` branch~~ postponed, see #199
- [x] Code coverage on http://coveralls.io
- [x] Address Sanitizer builds
- [x] ~~Memory / Undefined Behavior Sanitizer builds~~ postponed, see mosra/corrade#29
- [x] Drop the old Jenkins configs
- [x] Scheduled builds on Travis
- [ ] Scheduled builds on AppVeyor (https://www.appveyor.com/docs/build-configuration/#scheduled-builds)
- [x] Build all the the bootstrap projects (scheduled builds)

**Comment by mosra** [comment]
I'm currently evaulating AppVeyor, so far all builds fail either on tests (expected) and or on compilation issues (unexpected). Looks like it would be possible to provide pre-compiled binaries for each build (yay!), but as I'm limited by VM time and the VM is not particularly fast, there will probably be only one configuration of everything (Dynamic/Release) -- it takes 18 minutes (!) to build Magnum and run its tests! 

Currently MSVC 2013 on compatibility branch (yeah, can't wait to test MSVC 2015 on master tonight).

Links to live versions:
- [Corrade](https://ci.appveyor.com/project/mosra/corrade)
- [Magnum](https://ci.appveyor.com/project/mosra/magnum)
- [Magnum Plugins](https://ci.appveyor.com/project/mosra/magnum-plugins)
- [Magnum Examples](https://ci.appveyor.com/project/mosra/magnum-examples)

**Comment by mosra** [comment]
AppVeyor support is pretty much done. Each build produces ZIP file with dynamically compiled release libraries and executables.

**Comment by LB--** [comment]
How did the MSVC 2015 RTM test go?

**Comment by mosra** [comment]
@LB-- currently stuck on meaningless errors that weren't there with 2013. Will post the progress to #96, when there's any :)

**Comment by mosra** [comment]
Windows CI done (and green), next step is Travis for Linux.

**Comment by mosra** [comment]
OSX/Linux Travis CI build for Corrade [![Build Status](https://travis-ci.org/mosra/corrade.svg?branch=master)](https://travis-ci.org/mosra/corrade), Magnum [![Build Status](https://travis-ci.org/mosra/magnum.svg?branch=master)](https://travis-ci.org/mosra/magnum) and Magnum Plugins [![Build Status](https://travis-ci.org/mosra/magnum-plugins.svg?branch=master)](https://travis-ci.org/mosra/magnum-plugins) done. Their Linux environment is hopelessly outdated so I had to install/compile *a lot* of stuff manually. Ugh. There are also a few annoying issues with Linux filesystem (it's not able to differentiate between files and directories among other things), but after a few random tries and *ugly* workarounds I made it work.

The OSX environment is awesome in comparison. Never thought I would say that :)

For Magnum Integration and Magnum Examples I'm waiting for Travis to [include Bullet library in their Linux environment](https://github.com/travis-ci/apt-package-whitelist/issues/1190) (issue filled 2015-09-15). They are not exactly responsive so that might take a (longer) while.

**Comment by mosra** [comment]
Travis CI done (green except for failing BulletIntegration test on OSX). Gave up on waiting for Travis CI to include Bullet in their images.

**Comment by mosra** [comment]
iOS, Emscripten, MinGW, 64-bit MSVC and Windows RT CI builds are done now. Next step is Android.

**Comment by mosra** [comment]
Desktop GLES builds done on Linux and Windows (except for desktop GLES3 on Travis CI, because it has, *as usual*, hopelessly outdated GL packages), Android GLES2/GLES3 builds and tests done. Besides that, quite a few portability issues, bugs and memory leaks were fixed along the way in order to make the builds green.

Next step is finishing the ASan builds and building examples for iOS, Android and Emscripten.

**Comment by mosra** [comment]
AddressSanitizer builds are on all repos now (except examples), quite a few memory leaks were fixed along the way (the most important ones being in `StbImageImporter` and `StbPngImageConverter`, where a whole image was leaked every time).

**Comment by mosra** [comment]
GLES, iOS, Emscripten and Android ports of particular examples are tested on Travis CI and AppVeyor now.

**Comment by mosra** [comment]
GLES3 testing on Travis CI done by switching to 14.04, bootstrap projects are now built on the CI as well, ANGLE build was postponed to #206 and GL testing postponed to #207. Also I enabled scheduled builds on AppVeyor, giving it a day or two to see if they work. If they do, I'll *finally* be able to close this.

**Comment by mosra** [comment]
Scheduled builds on AppVeyor seem to work well. Closing as done.
